CREATE TABLE  customer_into
(
CUSTOMER_ID INTEGER NOT NULL,PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(64)  NOT NULL,
FIRST_NAME_IV VARCHAR(32),
FIRST_INITIAL VARCHAR(1),
LAST_NAME VARCHAR(64) NOT NULL,
LAST_NAME_IV VARCHAR(32),
LAST_INITIAL VARCHAR(1),
EMAIL_ADDRESS VARCHAR(64),
EMAIL_ADDRESS_IV VARCHAR(32),
ZIP_CODE VARCHAR(32),
CREDIT_CARD_NUM VARCHAR(64) NOT NULL,
CREDIT_CARD_NUM_IV VARCHAR(32),
LAST_FOUR_CCN VARCHAR(4),
EXPIRATION_DATE VARCHAR(32) NOT NULL,
EXPIRATION_DATE_IV VARCHAR(32),
PII_SCOPE_ALIAS_ID VARCHAR(30),
CCI_SCOPE_ALIAS_ID VARCHAR(30),
);


